name: trojan
services:
  web:
    image: nginx:alpine
    volumes:
      - ./cert/:/etc/nginx/cert/
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/web:/usr/share/nginx/html
    ports:
      - "${WEB_PORT}:80"
      # - "${WEB_SSL_PORT}:443"
    environment:
      - NGINX_HOST=${WEB_HOST}
      - WEB_SSL_PORT=${WEB_SSL_PORT:-$PORT}
      - TROJAN_WEB_PORT=${REMOTE_PORT:-8080}
    restart: on-failure
  trojan:
    build:
      context: ./trojan
      dockerfile: ./Dockerfile
    volumes:
      - ./cert:/etc/trojan/cert
      - ./trojan/templates:/etc/trojan-go/templates
    environment:
      - TROJAN_PASSWORD=${PASSWORD-}
      - TROJAN_HOST=${SSL_SNI-}
      - WS=${WS:-false}
      - WS_PATH=${WS_PATH-}
      - WS_HOST=${WS_HOST-}
      - SS=${SS:-false}
      - SS_PASSWORD=${SS_PASSWORD-}
      - REMOTE_ADDR=${REMOTE_ADDR:-web}
      - REMOTE_PORT=${REMOTE_PORT:-80}
      - FALLBACK_ADDR=${FALLBACK_ADDR-web}
      - FALLBACK_PORT=${FALLBACK_PORT-80}
    ports:
      - "${PORT}:443"
    depends_on:
      - web
    restart: on-failure
